// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFkcbL5Nqw1dWgCDVKQD8Je0nPJ8SxqPs',
    appId: '1:27639285747:web:55b0268d5a05dc36c1b486',
    messagingSenderId: '27639285747',
    projectId: 'docflutter-563f6',
    authDomain: 'docflutter-563f6.firebaseapp.com',
    storageBucket: 'docflutter-563f6.firebasestorage.app',
    measurementId: 'G-FLYRCBR9CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcEkbZzSBgPJB09FaRu43U_M47YE0cRD4',
    appId: '1:27639285747:android:7d343b553daddd20c1b486',
    messagingSenderId: '27639285747',
    projectId: 'docflutter-563f6',
    storageBucket: 'docflutter-563f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDceNeseyDHb8u6EIdBz_GWcH7-RsuFp4U',
    appId: '1:27639285747:ios:32c0c32152bf062ec1b486',
    messagingSenderId: '27639285747',
    projectId: 'docflutter-563f6',
    storageBucket: 'docflutter-563f6.firebasestorage.app',
    iosBundleId: 'com.example.docflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjEaME5gKTyZxbvJlTdpm0VHYKWM1FYs0',
    appId: '1:901969674822:ios:976686cae67bd9947e4047',
    messagingSenderId: '901969674822',
    projectId: 'device-streaming-7767db09',
    storageBucket: 'device-streaming-7767db09.firebasestorage.app',
    iosBundleId: 'com.example.docflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsYxDDhruOAFl2fXWAe7upwKh5eWLtzQM',
    appId: '1:901969674822:web:a8a3f1752f0bdff07e4047',
    messagingSenderId: '901969674822',
    projectId: 'device-streaming-7767db09',
    authDomain: 'device-streaming-7767db09.firebaseapp.com',
    storageBucket: 'device-streaming-7767db09.firebasestorage.app',
  );

}